//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankomatServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mainEntities : DbContext
    {
        public mainEntities()
            : base("name=mainEntities")
        {
            Database.Connection.ConnectionString = "Data Source=" + System.Web.Hosting.HostingEnvironment.MapPath("~/App_Data/BankomatDB.db") + ";Version=3;";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ConfirmKeys> ConfirmKeys { get; set; }
        public virtual DbSet<Phones> Phones { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
    }
}
