//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankomatServer
{
    using BankomatServer.Models.DataClasses;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    /// <summary>
    /// вид/статус карты
    /// </summary>
    [Serializable]
    public enum CardsStatuses
    {
        [XmlEnum(Name = "BlackCard")]
        BlackCard = 0,
        [XmlEnum(Name = "BlueCard")]
        BlueCard = 1,
        [XmlEnum(Name = "GoldCard")]
        GoldCard = 2,
    }
    [Serializable]
    public partial class Cards : BaseCard
    {
        public virtual Clients Clients { get; set; }

        /// <summary>
        /// приведение к базовому объекту для передачи через xmlSerializer
        /// </summary>
        /// <returns>BaseCard object</returns>
        public override BaseCard GetBaseObj()
        {
            BaseCard bc = new Cards();
            bc.Balance = Balance;
            bc.CardNumber = CardNumber;
            bc.CardStatus = CardStatus;
            bc.ClientId = ClientId;
            bc.DateOfEndUsing = DateOfEndUsing;
            bc.Id = Id;
            bc.IsBlocked = IsBlocked;
            bc.Pin = Pin;

            return bc;
        }
    }
}
