//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankomatServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public long Id { get; set; }
        public long CardId { get; set; }
        public long Form { get; set; }
        public double Sum { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
